version: "3"

services:
  mongo:
    image: mongo
    container_name: "sv_mongo"
    #restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  lanchonete:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
