application:
  title: "Aplicação desenvolvida por: AmandaPoreto, AndréMelchior e RichardDallaqua"

server:
  port: 8081
  servlet:
    context-path: /production-ms

queues:
  confirma_producao: confirma_producao

external:
  gateways:
    url: ${URL_PEDIDO:http://localhost:5000/pedido-ms}
    busca: "/api/v1/pedidos/{idPedido}/buscar"
    status: "/api/v1/pedidos/{idPedido}/status/{status}"