application:
  title: "Aplicação desenvolvida por: AmandaPoreto, AndréMelchior e RichardDallaqua"

server:
  port: 8080
  servlet:
    context-path: /production-ms

gateways:
  pedidos:
    busca: "http://localhost:5000/pedido-ms/api/v1/pedidos/{idPedido}/buscar"
    status: "http://localhost:5000/pedido-ms/api/v1/pedidos/{idPedido}/status/{status}"