apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.9-management
          ports:
            - containerPort: 5672 # Porta padrão para o RabbitMQ
            - containerPort: 15672 # Porta do painel de controle do RabbitMQ (opcional)
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: teste
            - name: RABBITMQ_DEFAULT_PASS
              value: teste
            - name: RABBITMQ_MANAGEMENT_PLUGIN
              value: "true"