name: AWS ECS Deploy

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-2

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
        run: |
          docker build -t fiap-producao-ms .
          docker tag  fiap-producao-ms:latest 637423657780.dkr.ecr.us-east-2.amazonaws.com/fiap-producao-ms:latest
          docker push 637423657780.dkr.ecr.us-east-2.amazonaws.com/fiap-producao-ms:latest